name: explora
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_rating_bar: ^3.0.1+1
  carousel_slider: ^1.3.0
  fluttertoast: ^4.0.1
  qr_code_scanner: ^0.0.12
  url_launcher: ^5.4.10
  cloud_firestore: ^0.13.6
  firebase_storage: ^3.1.6
  image_picker: ^0.5.3+1
  flutter_picker: ^1.1.5
  intl: ^0.15.7
  random_string: ^2.0.1



dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter


flutter_icons: 
  android: true
  ios: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/explora_icon_64px.png
    - assets/images/mail.png
    - assets/images/menu.png
    - assets/images/qr_code.png
    - assets/images/flight.png
    - assets/images/check_in.png
    - assets/images/protect.png
    - assets/images/lounge.png
    - assets/images/deals.png
    - assets/images/my_booking.png
    - assets/images/shield.png
    - assets/images/history.png
    - assets/images/travel_insurance.png
    - assets/images/on_time.png
    - assets/images/life_insurance.png
    - assets/images/allianz.png
    - assets/images/axa.png
    - assets/images/sinarmas.png
    - assets/images/zurich.png
    - assets/images/wallet.png
    - assets/images/app_settings.png
    - assets/images/help.png
    - assets/images/term_of_use.png
    - assets/images/points.png
    - assets/images/balance.png
    - assets/images/message.png
    - assets/images/origin.png
    - assets/images/destination.png
    - assets/images/departure_date.png
    - assets/images/passengers.png
    - assets/images/seat_class.png
    - assets/images/family_name.png
    - assets/images/depart_from.png
    - assets/images/booking_number.png
    - assets/images/edit.png
    - assets/images/my_account.png
    - assets/images/passport.png
    - assets/images/history1.png
    - assets/images/pattern.png
    - assets/images/bank/bca.png
    - assets/images/bank/bri.png
    - assets/images/bank/cimb_niaga.png
    - assets/images/bank/citybank.png
    - assets/images/bank/dbs.png
    - assets/images/bank/kdb.png
    - assets/images/bank/mandiri.png
    - assets/images/bank/uob.png
    - assets/images/atm.png
    - assets/images/debit_card.png
    - assets/images/mobile_banking.png
    - assets/images/pay.png
    - assets/images/payment.png
    - assets/images/refund.png
    - assets/images/top_up_balance.png
    - assets/images/top_up.png
    - assets/images/default_profile.png
    - assets/images/emily.jpg
    - assets/images/meal.png
    - assets/images/baggage.png
    - assets/images/traveler.png
    - assets/images/entertainment.png
    - assets/images/contact.png
    - assets/images/baggage1.png
    - assets/images/bank/alto.png
    - assets/images/bank/american_express.png
    - assets/images/bank/ana.png
    - assets/images/bank/atm_bersama.jpg
    - assets/images/bank/bca_klik_pay.png
    - assets/images/bank/mastercard.png
    - assets/images/bank/prima.png
    - assets/images/bank/visa.png
    - assets/images/tick.png
    - assets/images/seat.png
    - assets/images/banner_travel.jpg
    - assets/images/indonesia.png
    - assets/images/international.png
    - assets/images/map.png
    - assets/images/start_date.png
    - assets/images/end_date.png
    - assets/images/annual_trip.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin/Cabin-Regular.ttf
        - asset: assets/fonts/Cabin/Cabin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin/Cabin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin/Cabin-Bold.ttf
          weight: 700
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
